name: Fetch File from Another Repo

on:
  schedule:
    - cron: "10 6-18 * * *" # “At minute 0 past every hour from 6 through 18.”
  workflow_dispatch: # Allows the workflow to be manually triggered

jobs:
  fetch-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@main
        with:
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch file from another repository
        run: |
          mkdir -p fetched_files
          curl -o fetched_files/power-outages.json https://raw.githubusercontent.com/MrSunshyne/mauritius-dataset-electricity/main/data/power-outages.json

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          if [[ `git status --porcelain` ]]; then
            git add fetched_files/power-outages.json
            git commit -m 'Fetch file from target repository'
            git push
          else
            echo "WARNING: No changes were detected. git commit push action aborted."
          fi
        shell: bash
